//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.08.06 at 10:28:22 PM MSK 
//


package com.epam.training.tasks.task3.model.entity;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flowers", propOrder = {
    "flower"
})
@XmlRootElement(name = "flowers", namespace = "http://www.example.com/flowers")
public class Flowers {

    @XmlElementRef(name = "flower", namespace = "http://www.example.com/flowers", type = JAXBElement.class)
    protected List<Flower> flower;

    public List<Flower> getFlower() {
        if (flower == null) {
            flower = new ArrayList<Flower>();
        }
        return this.flower;
    }

    public List<Flower> getFlowers() {
        return flower;
    }
}
